import Head from "next/head";
import { ReactNode } from "react";
import { Icon } from "components/atoms";
import { Menu } from "@headlessui/react";
import clsx from "clsx";

function MenuBtn() {
  return (
    <Menu.Button className="bg-green-dark text-white p-5 rounded-bl-3xl">
      <span className="block w-6">
        <Icon.Menu />
      </span>

      <span className="sr-only">選單</span>
    </Menu.Button>
  );
}

const links = [
  { label: "最新消息", icon: <Icon.News />, href: "/" },
  {
    label: "預約訂車",
    icon: <Icon.Order />,
    items: [
      { label: "預約訂車", href: "/" },
      { label: "快速叫車", href: "/" },
    ],
  },
  { label: "訂單檢視", icon: <Icon.History />, href: "/" },
  { label: "用戶資料", icon: <Icon.User />, href: "/" },
  { label: "聯繫客服", icon: <Icon.Customer />, href: "/" },
  { label: "常見問題", icon: <Icon.QA />, href: "/" },
];

type MenuLinkProps = {
  href?: string;
  icon?: ReactNode;
  label: string;
  className?: string;
};
function MenuLink({ href, icon, label, className }: MenuLinkProps) {
  if (!href) {
    return (
      <div
        className={clsx(
          "inline-flex items-center space-x-6 py-4",
          "bg-green-dark text-white",
          className
        )}
      >
        <span className="w-8">{icon}</span>
        <span className="text-xl font-light">{label}</span>
      </div>
    );
  }

  return (
    <Menu.Item>
      {({ active }) => (
        <a
          href={href}
          className={clsx(
            "inline-flex items-center space-x-6 py-4",
            active ? "bg-green-darkest" : "bg-green-dark",
            active ? "text-gold-light" : "text-white",
            className
          )}
        >
          {icon ? (
            <span className="w-8">{icon}</span>
          ) : (
            <span className="bg-gold-light w-3 h-3 rounded-full" />
          )}

          <span className="text-xl font-light">{label}</span>
        </a>
      )}
    </Menu.Item>
  );
}

function Account() {
  return (
    <div className="bg-white rounded-b-3xl py-10 px-12 shadow">
      <p className="text-green-dark text-2xl font-bold">HI!訪客</p>
    </div>
  );
}

function MenuList() {
  return (
    <Menu.Items className="fixed top-0 -z-10 w-full h-screen bg-green-dark pt-14">
      <Account />

      <nav className="flex flex-col py-8">
        {links.map(({ label, icon, href, items }) =>
          items ? (
            <div>
              <MenuLink
                href={href}
                icon={icon}
                label={label}
                className="pl-12"
              />

              <div className="flex flex-col">
                {items.map(({ label, href }) => (
                  <MenuLink href={href} label={label} className="pl-24" />
                ))}
              </div>
            </div>
          ) : (
            <MenuLink href={href} icon={icon} label={label} className="pl-12" />
          )
        )}
      </nav>
    </Menu.Items>
  );
}

function Logo() {
  return (
    <div className="flex w-full items-center space-x-2 px-4 py-3">
      <img className="w-14" src="/images/logo.png" alt="高雄市政府預約訂平台" />

      <span className="text-green font-medium tracking-widest">
        高雄市政府預約訂平台
      </span>
    </div>
  );
}

function Header() {
  return (
    <Menu>
      <header className="shadow flex relative bg-white">
        <Logo />

        <MenuBtn />
      </header>

      <MenuList />
    </Menu>
  );
}

type Props = {
  children?: ReactNode;
};
export default function Default({ children }: Props) {
  return (
    <>
      <Head>
        <title>高雄市政府預約訂平台 | 首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>{children}</main>

      <footer></footer>
    </>
  );
}
