import Head from "next/head";
import { ReactNode } from "react";

type Props = {
  children?: ReactNode;
};
export default function Default({ children }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>

      <main>{children}</main>

      <footer></footer>
    </div>
  );
}
