import Head from "next/head";
import { ReactNode } from "react";
import Menu from "assets/icons/menu.svg";

function MenuBtn() {
  return (
    <button className="bg-green-dark text-white p-5 rounded-bl-3xl">
      <div className="w-6">
        <Menu />
      </div>
    </button>
  );
}

function Navbar() {
  return (
    <nav className="flex">
      <MenuBtn />
    </nav>
  );
}

function Logo() {
  return (
    <div className="flex w-full items-center space-x-2 px-4 py-3">
      <img className="w-14" src="/images/logo.png" alt="高雄市政府預約訂平台" />

      <span className="text-green font-medium tracking-widest">
        高雄市政府預約訂平台
      </span>
    </div>
  );
}

function Account() {
  return <div></div>;
}

function Header() {
  return (
    <header className="shadow flex">
      <Logo />

      <Navbar />

      <Account />
    </header>
  );
}

type Props = {
  children?: ReactNode;
};
export default function Default({ children }: Props) {
  return (
    <div>
      <Head>
        <title>高雄市政府預約訂平台 | 首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>{children}</main>

      <footer></footer>
    </div>
  );
}
